apiVersion: v1
kind: Service
metadata:
  name: discovery
  namespace: netpf
  labels:
    app: discovery
    tier: backend
spec:
  ports:
  - name: web
    port: 8761
    targetPort: 8761
  selector:
    app: discovery
    tier: backend
  type: LoadBalancer
