apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: discovery
  namespace: netpf
spec:
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: discovery
        tier: backend
    spec:
      containers:
      - name: discovery
        image: sipf/discovery-service:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8761
